---
- name: Ensure Xcode Command Line Tools are installed
  shell: xcode-select --install || true
  changed_when: false

# Ensure SSH directory exists
- name: Ensure ~/.ssh directory exists
  file:
    path: ~/.ssh
    state: directory
    mode: "0700"

# Generate SSH key pair
- name: Generate SSH key if it does not exist
  command: ssh-keygen -t ed25519 -C "{{ ssh_key_email }}" -f ~/.ssh/id_ed25519 -N ""
  args:
    creates: ~/.ssh/id_ed25519

# Add SSH private key to ssh-agent
- name: Add private key to ssh-agent with macOS keychain
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add --apple-use-keychain ~/.ssh/id_ed25519
  when: ansible_os_family == "Darwin"

# Output SSH public key
- name: Display SSH public key path
  debug:
    msg: "Public key is located at ~/.ssh/id_ed25519.pub"
